---
- name: locate rise src
  local_action: shell go list -f $(echo '((.Dir))' | tr '(' '{' | tr ')' '} ') {{rise_go_pkg}}
  register: rise_src
- name: cross compile binary
  local_action: shell go build -o build/rise {{rise_go_pkg}}
  environment:
    GOOS: "{{rise_go_os}}"
    GOARCH: "{{rise_go_arch}}"
- name: upload binary
  copy: src=build/rise dest={{rise_bin_path}} mode="u=rwx,g=rx,o=rx"
  sudo: true
- name: create {{rise_public_path}}
  file: path={{rise_public_path}} state=directory mode="u=rwx,g=rx,o=rx"
  sudo: true
- name: rsync assets
  synchronize: src={{rise_src.stdout}}/public/ dest={{rise_public_path}}/ rsync_path="sudo rsync"
- name: write init.d daemon script
  template: src=init.d-rise.j2 dest={{rise_init_path}} mode="u=rwx,g=rx,o=rx"
  sudo: true
- name: create {{rise_run_path|dirname}}
  file: path={{rise_run_path|dirname}} state=directory mode="u=rwx,g=rx,o=rx"
  sudo: true
- name: write run script
  template: src=rise-run.bash.j2 dest={{rise_run_path}} mode="u=rwx,g=rx,o=rx"
  sudo: true
- command: /bin/true
  notify: restart rise
